name: 1build-commons builder

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew clean build

      - name: Identify JAR File
        id: identify_jar
        run: |
          JAR_FILE=$(ls build/libs/*.jar | head -n 1)
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
          echo "JAR_NAME=$(basename $JAR_FILE)" >> $GITHUB_ENV

      - name: Upload JAR to Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Uploading JAR to repository..."
          curl -X PUT \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/java-archive" \
            --data-binary @${{ env.JAR_FILE }} \
            "https://api.github.com/repos/${{ github.repository }}/contents/${{ env.JAR_NAME }}?ref=main"
