name: 1build-commons builder

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew clean build

      - name: Identify JAR File
        id: identify_jar
        run: |
          JAR_FILE=$(ls build/libs/*.jar | head -n 1)
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
          echo "JAR_NAME=$(basename $JAR_FILE)" >> $GITHUB_ENV

      - name: Install AWS CLI
        run: |
          sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.ONEBUILD_AWS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.ONEBUILD_AWS_SECRET }}

      - name: Upload JAR to S3
        run: |
          echo "Uploading JAR to S3..."
          aws s3 cp "${{ env.JAR_FILE }}" "s3://1build-framework/1build-commons/${{ env.JAR_NAME }}"