name: Build Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle wrapper
        run: ./gradlew clean build

      - name: Upload JAR artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: 1build-commons
          path: build/libs/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: 1build-commons

      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Uploading release asset..."
          release_id=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/java-archive" \
            --data-binary @1build-commons.jar \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/$release_id/assets?name=1build-commons.jar"